/*
 * generated by Xtext 2.21.0
 */
package fr.cea.nabla.ui.graalvm;

import org.eclipse.core.runtime.Platform;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import fr.cea.nabla.ui.internal.NablaActivator;

public class NablabGraalVMExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return Platform.getBundle(Activator.PLUGIN_ID);
	}
	
	@Override
	protected Injector getInjector() {
		NablaActivator activator = NablaActivator.getInstance();
		return activator != null ? activator.getInjector(NablaActivator.FR_CEA_NABLA_NABLA) : null;
	}

}
